title: Deep Active Inference for Continuous Environments
subtitle: SFIS Presentation
shorttitle: Deep Active Inference
author: Tomasz Kawiak
shortauthor: T. Kawiak
institute: |
  Faculty of Electrical Engineering, Automation, Computer Science and Biomedical Engineering, AGH \
  Field of study: Computer Science and Intelligent Systems \
  Specialization: Artificial Intelligence and Data Analysis
shortinstitute: AIDA, ISI, EAIiIB, AGH
date: \today
lang: en-US # pl-PL # sudo apt install texlive-lang-polish
fontsize: 10pt
aspectratio: 169
theme: "AGHMM"
link-citations: true
# linkstyle: bold
section-titles: true
header-includes:
  - \setbeamertemplate{frametitle continuation}{}
